title: My Awesome GitHub Page
description: A new site powered by Jekyll and GitHub Pages.
theme: jekyll-theme-minimal # Use a standard GitHub theme or pick your own

# remote_theme: pages-themes/tactile@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
